const PLAYLIST_FILE = "/turks_nederland_setiptv.m3u";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
  "Access-Control-Allow-Headers": "*",
};

function corsHeaders(extra = {}) {
  return { ...CORS, ...extra };
}

function isGetPhpPath(pathname) {
  return pathname === "/get.php" || pathname === "/get.php/";
}

function validProviderStyleQuery(url) {
  const username = (url.searchParams.get("username") || "").trim();
  const password = (url.searchParams.get("password") || "").trim();
  const type = (url.searchParams.get("type") || "m3u_plus").toLowerCase();
  const output = (url.searchParams.get("output") || "mpegts").toLowerCase();

  // SETIPTV-compatible provider-style URL:
  // /get.php?username=...&password=...&type=m3u_plus&output=mpegts
  // We only require username/password to be present. The playlist itself is
  // still the public, authorised content already generated by the repository.
  if (!username || !password) return false;
  if (!["m3u", "m3u_plus"].includes(type)) return false;
  if (!["mpegts", "hls", "ts"].includes(output)) return false;

  return true;
}

async function servePlaylist(request, env) {
  const assetUrl = new URL(request.url);
  assetUrl.pathname = PLAYLIST_FILE;
  assetUrl.search = "";

  const response = await env.ASSETS.fetch(new Request(assetUrl.toString(), {
    method: request.method,
    headers: request.headers,
  }));

  if (!response.ok) {
    return new Response("Playlist file is not available yet.", {
      status: 503,
      headers: corsHeaders({
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": "no-store",
      }),
    });
  }

  const headers = new Headers(response.headers);

  // Use an explicit M3U content type rather than relying on file extension.
  headers.set("Content-Type", "application/x-mpegURL; charset=utf-8");
  headers.set("Cache-Control", "no-cache, no-store, must-revalidate");
  headers.set("Pragma", "no-cache");
  headers.set("Expires", "0");

  for (const [key, value] of Object.entries(CORS)) {
    headers.set(key, value);
  }

  return new Response(request.method === "HEAD" ? null : response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders() });
    }

    // Provider-style M3U endpoint for SETIPTV.
    if (isGetPhpPath(url.pathname)) {
      if (!["GET", "HEAD"].includes(request.method)) {
        return new Response("Method Not Allowed", {
          status: 405,
          headers: corsHeaders({ "Allow": "GET, HEAD, OPTIONS" }),
        });
      }

      if (!validProviderStyleQuery(url)) {
        return new Response(
          "Use /get.php?username=YOUR_USERNAME&password=YOUR_PASSWORD&type=m3u_plus&output=mpegts",
          {
            status: 400,
            headers: corsHeaders({
              "Content-Type": "text/plain; charset=utf-8",
              "Cache-Control": "no-store",
            }),
          }
        );
      }

      return servePlaylist(request, env);
    }

    if (url.pathname === "/health") {
      return new Response(JSON.stringify({
        ok: true,
        playlist: PLAYLIST_FILE,
        endpoint: "/get.php",
      }), {
        status: 200,
        headers: corsHeaders({
          "Content-Type": "application/json; charset=utf-8",
          "Cache-Control": "no-store",
        }),
      });
    }

    // Direct M3U URL remains available for debugging and ordinary players.
    return env.ASSETS.fetch(request);
  },
};
